# Generated by Django 6.0.6 on 2026-06-19 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critix', '0006_reviewlike_reviewreply_reviewreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewreply',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reviewreport',
            old_name='user',
            new_name='reporter',
        ),
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviewlike',
            name='value',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Offensive / Hate Speech'), ('spoiler', 'Spoilers'), ('irrelevant', 'Not relevant'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='critix.review'),
        ),
        migrations.AddConstraint(
            model_name='reviewlike',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='unique_review_like'),
        ),
        migrations.AddConstraint(
            model_name='reviewreport',
            constraint=models.UniqueConstraint(fields=('review', 'reporter'), name='unique_review_report'),
        ),
        migrations.RemoveField(
            model_name='reviewlike',
            name='is_like',
        ),
    ]
