# Generated by Django 6.0.6 on 2026-06-22 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critix', '0007_rename_text_reviewreply_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('dismissed', 'Report Dismissed'), ('review_deleted', 'Review Deleted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='critix.reviewreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
