# Generated by Django 6.0.6 on 2026-06-22 10:09
#
# This is identical to 0008_notification (the two were generated on parallel branches and
# later joined by 0010_merge_...). The table is created by 0008_notification, so here the model
# is only recorded in the migration *state*. Creating it in both made a fresh database (for
# example the test database) fail with: table "critix_notification" already exists.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critix', '0008_reviewreport_is_resolved_reportaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('notif_type', models.CharField(choices=[('blocked', 'Account Blocked'), ('unblocked', 'Account Unblocked'), ('review_removed', 'Review Removed'), ('warning', 'Warning'), ('general', 'General')], default='general', max_length=20)),
                        ('message', models.TextField()),
                        ('is_read', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
    ]