# Generated by Django 6.0.6 on 2026-06-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critix', '0008_notification'),
        ('critix', '0009_notification'),
    ]

    operations = [
    ]
