# Generated by Django 6.0.6 on 2026-06-23 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critix', '0012_watchedmovie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchedMovie',
            new_name='Watched',
        ),
    ]
