# Generated by Django 6.0.6 on 2026-06-23 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critix', '0013_rename_watchedmovie_watched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recentlyviewed',
            name='unique_user_movie_recently_viewed',
        ),
        migrations.AlterField(
            model_name='watched',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by_users', to='critix.movie'),
        ),
        migrations.AlterField(
            model_name='watched',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RecentlyViewed',
        ),
    ]
