# Generated by Django 6.1 on 2026-08-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critix', '0014_remove_recentlyviewed_unique_user_movie_recently_viewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='movie_cast/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='critix.movie')),
            ],
            options={
                'verbose_name': 'Movie cast member',
                'verbose_name_plural': 'Movie cast members',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MovieMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Photo'), ('trailer', 'Trailer')], default='image', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_media/')),
                ('url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='critix.movie')),
            ],
            options={
                'verbose_name': 'Movie media',
                'verbose_name_plural': 'Movie media',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
