# Generated by Django 6.1.1 on 2026-09-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critix', '0017_alter_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('poster_url', models.URLField(blank=True)),
                ('release_date', models.DateField()),
                ('trailer_url', models.URLField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_providers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='contains_spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
