# Generated by Django 6.1.1 on 2026-09-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critix', '0018_upcomingrelease_movie_watch_providers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
